-- membre / campus / batiment / piece / type de capteur / capteur /

CREATE TABLE IF NOT EXISTS `MEMBRE` (
  `idM` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NOT NULL,
  `prenom` VARCHAR(255) NOT NULL,
  `mdp` VARCHAR(32) NOT NULL,
  `sexe` VARCHAR(5) NOT NULL COMMENT 'Homme, Femme',
  `mail` VARCHAR(255) NOT NULL default '',
  PRIMARY KEY (`idM`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `CAMPUS` (
  `idC` INT(11) NOT NULL AUTO_INCREMENT,
  `nomC` VARCHAR(255) NOT NULL,
  `ville` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idC`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `BATIMENT` (
  `idB` INT(11) NOT NULL AUTO_INCREMENT,
  `nomB` VARCHAR(255) NOT NULL,
  `idC` INT(11) NOT NULL,
  PRIMARY KEY (`idB`),
  FOREIGN KEY (`idC`) REFERENCES `CAMPUS` (`idC`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `PIECE` (
  `idP` INT(11) NOT NULL AUTO_INCREMENT,
  `nomP` VARCHAR(255) NOT NULL,
  `idB` INT(11) NOT NULL,
  PRIMARY KEY (`idP`),
  FOREIGN KEY (`idB`) REFERENCES `BATIMENT` (`idB`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `TYPECAPTEUR` (
  `idTC` INT(11) NOT NULL AUTO_INCREMENT,
  `nomTC` VARCHAR(255) NOT NULL,
  `info` VARCHAR(255) NOT NULL,
  `logo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idTC`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `CAPTEUR` (
  `idCPT` INT(11) NOT NULL AUTO_INCREMENT,
  `idTCPT` INT(11) NOT NULL,
  PRIMARY KEY (`idCPT`),
  FOREIGN KEY (`idTCPT`) REFERENCES `TYPECAPTEUR` (`idTCPT`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1;